/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seleccion_colombia;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class editar extends javax.swing.JFrame {
 conector conecta = new conector();
        Connection con = conecta.getConexion();
    /**
     * Creates new form editar
     */
    public editar() {
        initComponents();
        mostrar6("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ape = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        posi = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        ed = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        equippo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        cami = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_datos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        id = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        camisa1 = new javax.swing.JRadioButton();
        btn_aceptar1 = new javax.swing.JButton();
        rdb_identificacion1 = new javax.swing.JRadioButton();
        rdb_nombres1 = new javax.swing.JRadioButton();
        rdb_apellidos1 = new javax.swing.JRadioButton();
        tlabel2 = new javax.swing.JLabel();
        buscar1 = new javax.swing.JTextField();
        edad1 = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setText("eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Edad");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Equipo donde juega");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Numero de camisa");

        ape.setBackground(new java.awt.Color(51, 153, 0));
        ape.setForeground(new java.awt.Color(255, 255, 255));
        ape.setBorder(null);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        posi.setBackground(new java.awt.Color(51, 153, 0));
        posi.setForeground(new java.awt.Color(255, 255, 255));
        posi.setBorder(null);

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        ed.setBackground(new java.awt.Color(51, 153, 0));
        ed.setForeground(new java.awt.Color(255, 255, 255));
        ed.setBorder(null);

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        equippo.setBackground(new java.awt.Color(51, 153, 0));
        equippo.setForeground(new java.awt.Color(255, 255, 255));
        equippo.setBorder(null);

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        cami.setBackground(new java.awt.Color(51, 153, 0));
        cami.setForeground(new java.awt.Color(255, 255, 255));
        cami.setBorder(null);

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombres");

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Apellidos");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Posición");

        nom.setBackground(new java.awt.Color(51, 153, 0));
        nom.setForeground(new java.awt.Color(255, 255, 255));
        nom.setBorder(null);

        Tbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_datos.setComponentPopupMenu(jPopupMenu1);
        jScrollPane1.setViewportView(Tbl_datos);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        id.setBackground(new java.awt.Color(51, 153, 0));
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setBorder(null);

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Identificacion");

        camisa1.setBackground(new java.awt.Color(51, 153, 0));
        camisa1.setText("camisa");

        btn_aceptar1.setText("Aceptar");
        btn_aceptar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_aceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptar1ActionPerformed(evt);
            }
        });

        rdb_identificacion1.setBackground(new java.awt.Color(51, 153, 0));
        rdb_identificacion1.setText("Identificacion");
        rdb_identificacion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_identificacion1ActionPerformed(evt);
            }
        });

        rdb_nombres1.setBackground(new java.awt.Color(51, 153, 0));
        rdb_nombres1.setText("Nombres");
        rdb_nombres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdb_nombres1ActionPerformed(evt);
            }
        });

        rdb_apellidos1.setBackground(new java.awt.Color(51, 153, 0));
        rdb_apellidos1.setText("Apellidos");

        tlabel2.setText("Valor a buscar:");

        buscar1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        buscar1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscar1KeyReleased(evt);
            }
        });

        edad1.setBackground(new java.awt.Color(51, 153, 0));
        edad1.setText("edad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cami)
                                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(44, 44, 44)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addComponent(ed)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(ape)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(equippo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(posi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tlabel2)
                        .addGap(18, 18, 18)
                        .addComponent(buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_aceptar1)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rdb_identificacion1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdb_nombres1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdb_apellidos1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edad1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(camisa1)
                        .addGap(92, 92, 92))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdb_identificacion1)
                    .addComponent(rdb_nombres1)
                    .addComponent(rdb_apellidos1)
                    .addComponent(edad1)
                    .addComponent(camisa1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tlabel2)
                    .addComponent(buscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_aceptar1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(posi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ape, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(equippo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ed, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cami, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        jMenuItem3.setText("Agregar Jugadores");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Buscar Jugadores");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Editar jugadores");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Inventario de Jugadores");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuItem7.setText("Salir");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int fila = Tbl_datos.getSelectedRow();
        if(fila>=0){
            id.setText(Tbl_datos.getValueAt(fila, 0).toString());
            nom.setText(Tbl_datos.getValueAt(fila, 1).toString());
            ape.setText(Tbl_datos.getValueAt(fila, 2).toString());
            posi.setText(Tbl_datos.getValueAt(fila, 3).toString());
            ed.setText(Tbl_datos.getValueAt(fila, 4).toString());
            equippo.setText(Tbl_datos.getValueAt(fila, 5).toString());
            cami.setText(Tbl_datos.getValueAt(fila, 6).toString());

        }
        else{
            JOptionPane.showMessageDialog(null, "No fue seleccionada");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int fila = Tbl_datos.getSelectedRow();
        String id="";
        id=Tbl_datos.getValueAt(fila, 0).toString();

        try {
            PreparedStatement pps = con.prepareStatement("DELETE FROM equipo WHERE id='"+id+"'");
            pps.executeUpdate();
            mostrar("");
        } catch (SQLException ex) {
            Logger.getLogger(editar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        agregar obj = new agregar();
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        busqueda obj = new busqueda();
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        editar obj = new editar();
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        inventario obj = new inventario();
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void btn_aceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptar1ActionPerformed

    }//GEN-LAST:event_btn_aceptar1ActionPerformed

    private void rdb_identificacion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_identificacion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_identificacion1ActionPerformed

    private void rdb_nombres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdb_nombres1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdb_nombres1ActionPerformed

    private void buscar1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscar1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_buscar1KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
             PreparedStatement pps = con.prepareStatement("UPDATE equipo SET id='"+id.getText()+"',nombres='"+nom.getText()+"',apellido='"+ape.getText()+"',posicion='"+posi.getText()+"',edad='"+ed.getText()+"',equipo='"+equippo.getText()+"',camisa='"+cami.getText()+"' WHERE id='"+id.getText()+"'");
             pps.executeUpdate();
             mostrar("");
             JOptionPane.showMessageDialog(null,"Actualizado con exito");
  
        } catch (SQLException ex) {
            Logger.getLogger(editar.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null,"No fue actualizado");
            
                }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editar().setVisible(true);
            }
        });
    }
    public  void mostrar(String nombre){
  DefaultTableModel  modelo = new DefaultTableModel();
  modelo.addColumn("id");
  modelo.addColumn("Nombres");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Posición");
        modelo.addColumn("Edad");
        modelo.addColumn("Equipo");
        modelo.addColumn("Camisa");
       Tbl_datos.setModel(modelo);
        String sql="";
        if(nombre.equals("")){
            sql="SELECT * FROM `equipo`";
            
            
        
        }else{
            sql="SELECT * FROM `equipo` WHERE id  like'%"+nombre+"%'";
        }
        String usuarios[]=new String[7];
        Statement set;
    try {
        set = con.createStatement();
        ResultSet result=set.executeQuery(sql);
        while(result.next()){
            usuarios[0]=result.getString(1);
            usuarios[1]=result.getString(2);
            usuarios[2]=result.getString(3);
            usuarios[3]=result.getString(4);
            usuarios[4]=result.getString(5);
            usuarios[5]=result.getString(6);
            usuarios[6]=result.getString(7);
            modelo.addRow(usuarios);
        }
        Tbl_datos.setModel(modelo);
    } catch (SQLException ex) {
        Logger.getLogger(inventario.class.getName()).log(Level.SEVERE, null, ex);
    }
        
}
public  void mostrar2(String nombre){
  DefaultTableModel  modelo = new DefaultTableModel();
  modelo.addColumn("id");
  modelo.addColumn("Nombres");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Posición");
        modelo.addColumn("Edad");
        modelo.addColumn("Equipo");
        modelo.addColumn("Camisa");
       Tbl_datos.setModel(modelo);
        String sql="";
        if(nombre.equals("")){
            sql="SELECT * FROM `equipo`";
            
            
        
        }else{
            sql="SELECT * FROM `equipo` WHERE nombres like'%"+nombre+"%'";
        }
        String usuarios[]=new String[7];
        Statement set;
    try {
        set = con.createStatement();
        ResultSet result=set.executeQuery(sql);
        while(result.next()){
            usuarios[0]=result.getString(1);
            usuarios[1]=result.getString(2);
            usuarios[2]=result.getString(3);
            usuarios[3]=result.getString(4);
            usuarios[4]=result.getString(5);
            usuarios[5]=result.getString(6);
            usuarios[6]=result.getString(7);
            modelo.addRow(usuarios);
        }
        Tbl_datos.setModel(modelo);
    } catch (SQLException ex) {
        Logger.getLogger(inventario.class.getName()).log(Level.SEVERE, null, ex);
    }
        
}
public  void mostrar3(String nombre){
  DefaultTableModel  modelo = new DefaultTableModel();
  modelo.addColumn("id");
  modelo.addColumn("Nombres");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Posición");
        modelo.addColumn("Edad");
        modelo.addColumn("Equipo");
        modelo.addColumn("Camisa");
       Tbl_datos.setModel(modelo);
        String sql="";
        if(nombre.equals("")){
            sql="SELECT * FROM `equipo`";
            
            
        
        }else{
            sql="SELECT * FROM `equipo` WHERE apellido like'%"+nombre+"%'";
        }
        String usuarios[]=new String[7];
        Statement set;
    try {
        set = con.createStatement();
        ResultSet result=set.executeQuery(sql);
        while(result.next()){
            usuarios[0]=result.getString(1);
            usuarios[1]=result.getString(2);
            usuarios[2]=result.getString(3);
            usuarios[3]=result.getString(4);
            usuarios[4]=result.getString(5);
            usuarios[5]=result.getString(6);
            usuarios[6]=result.getString(7);
            modelo.addRow(usuarios);
        }
        Tbl_datos.setModel(modelo);
    } catch (SQLException ex) {
        Logger.getLogger(inventario.class.getName()).log(Level.SEVERE, null, ex);
    }
        
}
public  void mostrar4(String nombre){
  DefaultTableModel  modelo = new DefaultTableModel();
  modelo.addColumn("id");
  modelo.addColumn("Nombres");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Posición");
        modelo.addColumn("Edad");
        modelo.addColumn("Equipo");
        modelo.addColumn("Camisa");
       Tbl_datos.setModel(modelo);
        String sql="";
        if(nombre.equals("")){
            sql="SELECT * FROM `equipo`";
            
            
        
        }else{
            sql="SELECT * FROM `equipo`WHERE edad like'%"+nombre+"%'";
        }
        String usuarios[]=new String[7];
        Statement set;
    try {
        set = con.createStatement();
        ResultSet result=set.executeQuery(sql);
        while(result.next()){
            usuarios[0]=result.getString(1);
            usuarios[1]=result.getString(2);
            usuarios[2]=result.getString(3);
            usuarios[3]=result.getString(4);
            usuarios[4]=result.getString(5);
            usuarios[5]=result.getString(6);
            usuarios[6]=result.getString(7);
            modelo.addRow(usuarios);
        }
        Tbl_datos.setModel(modelo);
    } catch (SQLException ex) {
        Logger.getLogger(inventario.class.getName()).log(Level.SEVERE, null, ex);
    }
        
}
public  void mostrar5(String nombre){
  DefaultTableModel  modelo = new DefaultTableModel();
  modelo.addColumn("id");
  modelo.addColumn("Nombres");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Posición");
        modelo.addColumn("Edad");
        modelo.addColumn("Equipo");
        modelo.addColumn("Camisa");
       Tbl_datos.setModel(modelo);
        String sql="";
        if(nombre.equals("")){
            sql="SELECT * FROM `equipo`";
            
            
        
        }else{
            sql="SELECT * FROM `equipo` WHERE camisa like'%"+nombre+"%'";
        }
        String usuarios[]=new String[7];
        Statement set;
    try {
        set = con.createStatement();
        ResultSet result=set.executeQuery(sql);
        while(result.next()){
            usuarios[0]=result.getString(1);
            usuarios[1]=result.getString(2);
            usuarios[2]=result.getString(3);
            usuarios[3]=result.getString(4);
            usuarios[4]=result.getString(5);
            usuarios[5]=result.getString(6);
            usuarios[6]=result.getString(7);
            modelo.addRow(usuarios);
        }
        Tbl_datos.setModel(modelo);
    } catch (SQLException ex) {
        Logger.getLogger(inventario.class.getName()).log(Level.SEVERE, null, ex);
    }
        
}
public  void mostrar6(String nombre){
  DefaultTableModel  modelo = new DefaultTableModel();
  modelo.addColumn("id");
  modelo.addColumn("Nombres");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Posición");
        modelo.addColumn("Edad");
        modelo.addColumn("Equipo");
        modelo.addColumn("Camisa");
       Tbl_datos.setModel(modelo);
        String sql="";
        if(nombre.equals("")){
            sql="SELECT * FROM `equipo`";
            
            
        
        }else{
            sql="SELECT * FROM `equipo`";
        }
        String usuarios[]=new String[7];
        Statement set;
    try {
        set = con.createStatement();
        ResultSet result=set.executeQuery(sql);
        while(result.next()){
            usuarios[0]=result.getString(1);
            usuarios[1]=result.getString(2);
            usuarios[2]=result.getString(3);
            usuarios[3]=result.getString(4);
            usuarios[4]=result.getString(5);
            usuarios[5]=result.getString(6);
            usuarios[6]=result.getString(7);
            modelo.addRow(usuarios);
        }
        Tbl_datos.setModel(modelo);
    } catch (SQLException ex) {
        Logger.getLogger(inventario.class.getName()).log(Level.SEVERE, null, ex);
    }
        
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tbl_datos;
    private javax.swing.JTextField ape;
    public javax.swing.JButton btn_aceptar1;
    public javax.swing.JTextField buscar1;
    private javax.swing.JTextField cami;
    public javax.swing.JRadioButton camisa1;
    private javax.swing.JTextField ed;
    public javax.swing.JRadioButton edad1;
    private javax.swing.JTextField equippo;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField posi;
    public javax.swing.JRadioButton rdb_apellidos1;
    public javax.swing.JRadioButton rdb_identificacion1;
    public javax.swing.JRadioButton rdb_nombres1;
    public javax.swing.JLabel tlabel2;
    // End of variables declaration//GEN-END:variables
}
